use crate::ast::{FieldType, ModelDef, SchemaFile};
use crate::codegen::GeneratedFile;
use crate::error::DslError;

pub fn generate(schema: &SchemaFile) -> Result<Vec<GeneratedFile>, DslError> {
    let mut content = String::from(
        "// This file is generated by the Anti-Gravital DSL compiler. Do not edit manually.\n\
         use serde::{Deserialize, Serialize};\n\n",
    );

    for model in &schema.models {
        content.push_str(&generate_model(model));
        content.push('\n');
    }

    Ok(vec![GeneratedFile {
        path: "src/generated/models.rs".into(),
        content,
    }])
}

fn generate_model(model: &ModelDef) -> String {
    let mut out = String::new();
    out.push_str("#[derive(Debug, Clone, Serialize, Deserialize)]\n");
    out.push_str(&format!("pub struct {} {{\n", model.name));

    for field in &model.fields {
        let rust_type = field_type_to_rust(&field.ty);
        let ty = if field.optional {
            format!("Option<{rust_type}>")
        } else {
            rust_type
        };
        out.push_str(&format!("    pub {}: {},\n", field.name, ty));
    }

    out.push_str("}\n");
    out
}

fn field_type_to_rust(ty: &FieldType) -> String {
    match ty {
        FieldType::Uuid => "uuid::Uuid".into(),
        FieldType::Email => "String".into(),
        FieldType::String => "String".into(),
        FieldType::Int => "i64".into(),
        FieldType::Float => "f64".into(),
        FieldType::Bool => "bool".into(),
        FieldType::Timestamp => "chrono::DateTime<chrono::Utc>".into(),
        FieldType::Json => "serde_json::Value".into(),
        FieldType::Model(name) => name.clone(),
        FieldType::Array(inner) => format!("Vec<{}>", field_type_to_rust(inner)),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ast::{Directive, FieldDef, ModelDef};

    #[test]
    fn generates_struct_from_model() {
        let model = ModelDef {
            name: "User".into(),
            fields: vec![
                FieldDef {
                    name: "id".into(),
                    ty: FieldType::Uuid,
                    directives: vec![Directive::Primary],
                    optional: false,
                },
                FieldDef {
                    name: "email".into(),
                    ty: FieldType::Email,
                    directives: vec![],
                    optional: false,
                },
            ],
        };
        let src = generate_model(&model);
        assert!(src.contains("pub struct User"));
        assert!(src.contains("pub id: uuid::Uuid"));
        assert!(src.contains("pub email: String"));
    }
}
