use crate::ast::{FieldType, ModelDef, SchemaFile};
use crate::codegen::GeneratedFile;
use crate::error::DslError;

pub fn generate(schema: &SchemaFile) -> Result<Vec<GeneratedFile>, DslError> {
    let mut content = String::from(
        "// This file is generated by the Anti-Gravital DSL compiler. Do not edit manually.\n\n",
    );

    for model in &schema.models {
        content.push_str(&generate_interface(model));
        content.push('\n');
    }

    Ok(vec![GeneratedFile {
        path: "src/generated/models.ts".into(),
        content,
    }])
}

fn generate_interface(model: &ModelDef) -> String {
    let mut out = String::new();
    out.push_str(&format!("export interface {} {{\n", model.name));

    for field in &model.fields {
        let ts_type = field_type_to_ts(&field.ty);
        let opt = if field.optional { "?" } else { "" };
        out.push_str(&format!("  {}{}: {};\n", field.name, opt, ts_type));
    }

    out.push_str("}\n");
    out
}

fn field_type_to_ts(ty: &FieldType) -> &'static str {
    match ty {
        FieldType::Uuid => "string",
        FieldType::Email => "string",
        FieldType::String => "string",
        FieldType::Int => "number",
        FieldType::Float => "number",
        FieldType::Bool => "boolean",
        FieldType::Timestamp => "string",
        FieldType::Json => "unknown",
        FieldType::Model(_) => "object",
        FieldType::Array(_) => "unknown[]",
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ast::{FieldDef, ModelDef};

    #[test]
    fn generates_interface() {
        let model = ModelDef {
            name: "Product".into(),
            fields: vec![FieldDef {
                name: "price".into(),
                ty: FieldType::Float,
                directives: vec![],
                optional: false,
            }],
        };
        let src = generate_interface(&model);
        assert!(src.contains("export interface Product"));
        assert!(src.contains("price: number"));
    }
}
